There are multiple ways to position nodes in PONS.
They can either be set manually or loaded from an existing graph structure.
Alternatively, if you use an external movement model such as *ONE* or *ns2*, these will set node positions accordingly.

For the rest of this section, we will look at different ways to create the following topology:

[mermaid, "topo", png]
....
graph TD;
    n1---n2;
    n1---n3;
    n2---n4;
    n3---n4;
....

=== Manual Node Positions

Each node has `.x`, `.y` and `.z` values as floats that can be manipulated after creating the node.
```python
n1 = pons.Node(1, "n1", 
  net=[pons.NetworkSettings("WIFI_40m", range=40)], 
  router=pons.routing.EpidemicRouter(capacity=CAPACITY)
)
n1.x = 50
n1.y = 50

n2 = pons.Node(1, "n2", 
  net=[pons.NetworkSettings("WIFI_40m", range=40)], 
  router=pons.routing.EpidemicRouter(capacity=CAPACITY)
)
n2.x = 25
n2.y = 75

n3 = pons.Node(1, "n3", 
  net=[pons.NetworkSettings("WIFI_40m", range=40)], 
  router=pons.routing.EpidemicRouter(capacity=CAPACITY)
)
n3.x = 75
n3.y = 75

n4 = pons.Node(1, "n4", 
  net=[pons.NetworkSettings("WIFI_40m", range=40)], 
  router=pons.routing.EpidemicRouter(capacity=CAPACITY)
)
n4.x = 50
n4.y = 100
```

We now created all 4 nodes with an epidemic router and a WLAN network with 40 meters of range.
Thus, n1 can barely reach n2 and n3 but not n4.
Alternatively, a contact plan could be used to provide fixed connections, see the following examples on how to build such topologies.

=== NetworkX Graph

If actual positions are not as important as the general network graph, it is very convenient to use [networkx](https://networkx.org/) for modelling the network.

```python
topo = nx.graph.Graph()
topo.add_node(1)
topo.add_node(2)
topo.add_node(3)
topo.add_node(4)
topo.add_edge(1, 2)
topo.add_edge(1, 3)
topo.add_edge(2, 4)
topo.add_edge(3, 4)

plan = pons.net.NetworkPlan(topo)
net = pons.NetworkSettings("networkplan", range=0, contactplan=plan)

nodes = pons.generate_nodes_from_graph(
    topo,
    router=pons.routing.EpidemicRouter(capacity=CAPACITY),
    net=[net],
)
```

We can use the `NetworkPlan` class to derive a contact plan for all graph edges. This can be supplied to our `NetworkSettings`, a `range` is not needed anymore as all links are fixed through the network contact plan.

Similar to the `generate_nodes` helper from the [tutorial](example.md), there is a helper to generate nodes from a given graph object that we can use (`generate_nodes_from_graph`).

==== Generating random topologies

The build in functions of `networkx` make it pretty easy to quickly generate random graphs that can be used as network topologies.

```python
topo1 = nx.erdos_renyi_graph(NUM_NODES, 0.3)
topo2 = nx.watts_strogatz_graph(NUM_NODES, 2, 0.3)
```

They can then just be used as the manually created one in the previous example.

==== GraphML

Building complex topologies manually can be cumbersome, therefore, PONS supports of loading graphml files with node information.
These can be generated by external tools.
Graphml is very powerful and depending on the tools can have additional extra information.
If using [netedit`](tools/netedit.md) to generate the graphml file one can also set the node *ID*, *name* and coordinates (*x* and *y*).

Loading a graphml file as a contact plan and creating the nodes from it is pretty straight forward:

```python
plan = pons.net.NetworkPlan.from_graphml("4n-diamond.graphml")

print(plan.nodes())
print(plan.connections())

net = pons.NetworkSettings("networkplan", range=0, contactplan=plan)

nodes = pons.generate_nodes_from_graph(
  plan.G, 
  router=pons.routing.EpidemicRouter(), 
  contactplan=plan
)

```
